apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>ConfigMap For Nginx</title>
    </head>
    <body>

    <h1>This is coming from Config Map</h1>
    <p>techbleat training programme ends today!.</p>

    </body>
    </html>