apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: loginapp
  name: pythonapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: loginapp
  type: LoadBalancer
status:
  loadBalancer: {}